// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

//go:generate mockgen -destination ./user_mock.go -package userclient -source $GOFILE

package userclient

import (
	"context"

	"user/user"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	LoginRequest     = user.LoginRequest
	RegisterRequest  = user.RegisterRequest
	GetUserRequset   = user.GetUserRequset
	LoginResponse    = user.LoginResponse
	RegisterResponse = user.RegisterResponse
	GetUserResponse  = user.GetUserResponse

	User interface {
		Login(ctx context.Context, in *LoginRequest) (*LoginResponse, error)
		Register(ctx context.Context, in *RegisterRequest) (*RegisterResponse, error)
		GetUser(ctx context.Context, in *GetUserRequset) (*GetUserResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Login(ctx context.Context, in *LoginRequest) (*LoginResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in)
}

func (m *defaultUser) Register(ctx context.Context, in *RegisterRequest) (*RegisterResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Register(ctx, in)
}

func (m *defaultUser) GetUser(ctx context.Context, in *GetUserRequset) (*GetUserResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUser(ctx, in)
}
